# Generated by Django 5.0b1 on 2023-12-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cashier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="change",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="debt",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="seller",
            name="change",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="seller",
            name="debt",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
