# Generated by Django 5.0 on 2023-12-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cashier", "0002_customer_change_customer_debt_seller_change_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceAdminProxy",
            fields=[],
            options={
                "verbose_name": "الفاتورة",
                "verbose_name_plural": "الفواتير",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("Cashier.invoice",),
        ),
        migrations.CreateModel(
            name="ProductAdminProxy",
            fields=[],
            options={
                "verbose_name": "المنتج",
                "verbose_name_plural": "المنتجات",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("Cashier.product",),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.FloatField(default=0.0),
        ),
    ]
