# Generated by Django 5.0 on 2024-01-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cashier", "0003_invoiceadminproxy_productadminproxy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
