# Generated by Django 5.0 on 2024-01-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cashier", "0004_invoice_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="custom_id",
            field=models.CharField(
                editable=False, max_length=20, null=True, unique=True
            ),
        ),
    ]
